services:
  app:
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  mysql:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
