name: Laravel CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: mbstring, pdo, sqlite
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Configure Environment
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=database/database.sqlite" >> .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node Dependencies
        run: npm install

      - name: Build Frontend Assets
        run: npm run build

      - name: Run Database Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test