name: Laravel CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: optical_crm_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: mbstring,pdo,pdo_mysql
          coverage: none

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: cp .env.example .env

      - name: Configure Database
        run: |
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=optical_crm_test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - run: composer install --no-interaction --prefer-dist

      - run: php artisan key:generate

      - run: npm install

      - run: npm run build

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent
          do
            sleep 2
          done

      - run: php artisan migrate --force

      - run: php artisan test

  deploy:
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Deploy Application
        run: |
          cd /home/mhd/CRM_optical

          git fetch origin
          git reset --hard origin/main

          docker compose down

          docker compose up -d --build

          echo "Waiting for MySQL..."

          until docker compose exec -T mysql mysqladmin ping -hlocalhost --silent
          do
            sleep 2
          done

          echo "MySQL is ready."

          docker compose exec -T app php artisan migrate --force

          docker compose exec -T app php artisan optimize:clear

          docker compose exec -T app php artisan optimize

          echo "✅ Deployment finished successfully!"
